### ISSUE TITLE
Incompatibilty with certain VanillaTweaks resource packs (specific pack presently unknown) EDIT: Pack is Proper Break Particles [VanillaTweaks.net]

### ISSUE THREAD

**Issue by NoComment1105** [FakeDomi/FastChest#1]
Hi!
My laptop doesn't have the best hardware for games and as a result, I'm always on the lookout for optimisation mods, usually using the mod pack fabulously optimised as a reference point.
I started using this mod and discovered that single chest models don't render. The same goes for ender chests. They do not show up in the crafting book, crafting result, inventory and when place down.
Then, following your advice from CurseForge, you said it may be resource pack related, i removed my main resource pack and it fixed the issue. Trouble is, i use a fair few packs. :/
I have attached some screen shots of the issue, followed by what happens when my resource pack is removed and a copy of selectedpacks.txt from my vanilla tweaks resource pack
![2021-01-30_07 10 43](https://user-images.githubusercontent.com/67918617/106350233-0912a780-62cc-11eb-93fd-b07d4b75c77d.png)
![2021-01-30_07 11 07](https://user-images.githubusercontent.com/67918617/106350238-0dd75b80-62cc-11eb-991a-fd0ecd04fb2a.png)
![2021-01-30_07 11 21](https://user-images.githubusercontent.com/67918617/106350242-14fe6980-62cc-11eb-8934-6a4a0e3f07eb.png)
![2021-01-30_07 11 23](https://user-images.githubusercontent.com/67918617/106350246-192a8700-62cc-11eb-9136-2ea64fc5891d.png)
![2021-01-30_07 12 13](https://user-images.githubusercontent.com/67918617/106350249-1b8ce100-62cc-11eb-9f89-43acf1680b76.png)

[Selected Packs.txt](https://github.com/FakeDomi/FastChest/files/5897538/Selected.Packs.txt)

**Comment by FakeDomi** [comment]
Well, one of your resource packs is overwriting `/resources/assets/minecraft/blockstats/chest.json` (and `ender_chest.json`). If you don't want to figure out which pack does that you could make this mod's `resources` folder a resource pack and set it to highest priority in your game.

**Comment by NoComment1105** [comment]
Ah thanks for responding so quick. Makes sense though I feel like it would be beneficial to you and your mod if I did find out which pack it had issues with, then you could mark incompatibility with it. Let me know if you want me to do so. Thanks

**Comment by NoComment1105** [comment]
But actually up looking through the entire resorce pack folder i was unable to find a `chest.json` or an `ender_chest.json` I will still try what you said regardless

**Comment by NoComment1105** [comment]
Although saying that i have found the issue. It seems that your mod is incompatible with Proper Break Particles from the vanilla tweaks library. I looked through my pack and i found only 1 set of chest based files and each one had link to proper break particles and removing it has shown that it does fix hte issue. If you would like to mark incompatability and close this issue that would be fine

**Comment by FakeDomi** [comment]
I added a note on the cf page. I don't think you can mark mods as incompatible with specific resource packs and it wouldn't even make much sense to do that in the first place, since the user can just remove the conflicting blockstate definitions from the resource pack.

**Comment by NoComment1105** [comment]
Oh okay well nevermind, Thanks for the help. And great mod i can already see the improvement
