### ISSUE TITLE
Doesn't work with Iron Chests for Fabric

### ISSUE THREAD

**Issue by globalista-dev** [FakeDomi/FastChest#14]
[Iron Chests for Fabric](https://www.curseforge.com/minecraft/mc-mods/iron-chests-for-fabric)'s chests can't be rendered as static blocks, which is what FastChest does. It looks like Minecraft tries to render the chest both as a dynamic models and as a static one. I'm not sure which mod is responsible. 

![2022-02-14_18 32 20_2](https://user-images.githubusercontent.com/35036442/153949990-085a7900-1cc3-4e58-a5dd-0e8029dcc7dd.png)

![2022-02-14_18 28 07](https://user-images.githubusercontent.com/35036442/153949727-c7002c69-474f-4bc4-8a7e-6691a394af2e.png)
.

**Comment by FakeDomi** [comment]
I fixed this on the FastChest side now, to make them rotate properly I'll also have to get some changes to the block state jsons merged into Iron Chests.

**Comment by FakeDomi** [comment]
https://github.com/4nner/IronChests/pull/20
