### ISSUE TITLE
Chests not appearing 

### ISSUE THREAD

**Issue by vitalyusa** [FakeDomi/FastChest#17]
im using 1.19 fabric with 1.19 fast chest mod and all ender chests not appearing and wooden as well, especially in new generation!

[2022-07-05_02 20 02](https://user-images.githubusercontent.com/108719857/177273039-7474f0d3-b5e2-4371-a3c8-8513f2bb11eb.png)
![2022-07-05_02 20 21](https://user-images.githubusercontent.com/108719857/177273047-94587b44-f3ea-4b57-8c71-8c4abd4a85c1.png)
![2022-07-05_02 20 41](https://user-images.githubusercontent.com/108719857/177273056-33622e5f-b2af-421b-9c9e-1cf5f20d4e77.png)
s

**Comment by FakeDomi** [comment]
Please read the last paragraph of the readme and make sure that it's none of your texture packs causing this issue.

**Comment by vitalyusa** [comment]
Yep, it was vanilla tweaks, idk what i added there that it causing it,
