### ISSUE TITLE
Chest animations do not run

### ISSUE THREAD

**Issue by NoComment1105** [FakeDomi/FastChest#2]
HELLO, me again
Sorry to bombard you with issues but it presently appears that the chest opening/closing animations do *not* run when opening and closing a chest
Now this i have no idea what is causing the issue like last time
[video.zip](https://github.com/FakeDomi/FastChest/files/5898360/video.zip)

**Comment by inikishev** [comment]
> HELLO, me again
> Sorry to bombard you with issues but it presently appears that the chest opening/closing animations do _not_ run when opening and closing a chest
> Now this i have no idea what is causing the issue like last time
> [video.zip](https://github.com/FakeDomi/FastChest/files/5898360/video.zip)

I am pretty sure this is literally what this mod does to improve performance

**Comment by NoComment1105** [comment]
Is it? I thought it changed the models not the animation

**Comment by inikishev** [comment]
> Is it? I thought it changed the models not the animation

Well it change models to static ones like all other blocks that don't animate

**Comment by NoComment1105** [comment]
Oh well this is a spoon moment, sorry

**Comment by FakeDomi** [comment]
It was kinda implied in the description. I put an explicit note now.
The reason why it is this way? Cause I couldn't think of a simple solution to make the one chest you are looking at have an opening animation without all the other chests shredding your fps. It's certainly possible but would require major patching of how Minecraft renders things and/or ugly hacks.
Also, I think this serves as a nice lesson about adding "magical performance mods" without understanding their implications :)

**Comment by NoComment1105** [comment]
Very true.
