### ISSUE TITLE
When using resource packs, chests can become invisible.

### ISSUE THREAD

**Issue by grimSagely** [FakeDomi/FastChest#21]
For StayTrue specifically, the chest item (in your/an inventory) becomes invisible. I could go through and test the RPs I disgarded assuming that there was conflicts between RPs, but assume the potential for a problem in any circumstance where a resource pack is modifying a chest. Sometimes this is only chest, sometimes this is enderchest as well, sometimes only the item, sometimes the entity placed in world.

**Comment by grimSagely** [comment]
mb, no coffee yet. feel free to mark this as working as intended or otherwise, I just had trouble searching for a fix (seo only gave me resource packs to MAKE the chest invisible as opposed to this incompatibility)

**Comment by FakeDomi** [comment]
The description page also tells you what files to remove from the resource pack to make them compatible.
