### ISSUE TITLE
[Request] Dynamic chest rendering

### ISSUE THREAD

**Issue by derech1e** [FakeDomi/FastChest#23]
Could you please add the function that chests are rendered dynamically. Say for example that all chests in a 4 block radius are rendered as tile entities and not as blocks/models. Personally, I tried to check if the block looked at by the player is a chest or not. It worked almost, but I ultimately failed on the implementation of double chests. 

I would love to keep the animation for the "close" chests. It may just be another option in the settings.

Thanks!

**Comment by FakeDomi** [comment]
You can use https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities, which does have a feature to restore chest animations. My mod is very limited in scope, so I'm not adding any extra quality features.
