### ISSUE TITLE
Version 1.19.4

### ISSUE THREAD

**Issue by alessandrofasse** [FakeDomi/FastChest#28]
Would it be possible to support the newest Minecraft version?

**Comment by FakeDomi** [comment]
Are there any issues? Usually it should work with older builds too (1.19.3 was an exception).

**Comment by alessandrofasse** [comment]
Thanks for the quick reply. I have to admit that I did not check it but I will in a couple of minutes. My idea was that if explicitly 1.19.3 is mentioned it works only on this version. Give ma a second to try it

**Comment by alessandrofasse** [comment]
Ok I can confirm that i works with version 1.19.4
