### ISSUE TITLE
[META] I've ported FastChest to Forge

### ISSUE THREAD

**Issue by globalista-dev** [FakeDomi/FastChest#33]
This isn't an issue, but I figured this was the quickest way to get in touch.

I've quickly ported FastChest to Forge for personal use on a Forge server with friends. If you're okay with it I can properly port, test and maintain the Forge version of the mod.

Let me know!

**Comment by FakeDomi** [comment]
Sure, the license allows it. I can link to the port when you've published it, multiple people asked for a forge version already.

**Comment by globalista-dev** [comment]
Great! I'll finish the port today, test the mod and send it to you. It's already on [GitHub](https://github.com/globalista-dev/fastchest_reforged), but it's not 100% done. I'll also close this issue.

**Comment by globalista-dev** [comment]
It's done. Working on 1.20, 1.20.1 and 1.20.2.

I've already uploaded it to GitHub and will post on CurseForge as well, with a link for the Fabric version here on GitHub.

**Comment by globalista-dev** [comment]
It's up on [CurseForge ](https://www.curseforge.com/minecraft/mc-mods/fastchest-reforged) as well. Feel free to link either one.

**Comment by globalista-dev** [comment]
Mandatory update: after some time on a break from modding, I've ported FastChest's 1.6 version to Forge. I've skipped 1.5, because there is no real reason to do it. It's up on CurseForge and now on [Modrinth](https://modrinth.com/mod/fastchest-reforged) as well. The Modrinth page might not be public, it's under review, but it will be in the next few days.
