### ISSUE TITLE
incompatible with create mod

### ISSUE THREAD

**Issue by ipiiia** [FakeDomi/FastChest#36]
Running with create fabric 1.20.1 does not remove the animation

**Comment by FakeDomi** [comment]
Flywheel (a dependency of Create) replaces the vanilla chest renderer with a more efficient one. I don't think there's anything to do for me here, but if you want you can measure the performance impact of having a bunch of chests with this mod vs Create.

**Comment by FakeDomi** [comment]
Just reply here if you want to add more information
