### ISSUE TITLE
Suggestion for making it still "Animate"

### ISSUE THREAD

**Issue by MonotoneDevelopment** [FakeDomi/FastChest#37]
So, you know how the furnace is a container item, but still a static block? And when you hit certain conditions, it changes its blockstate, and then changes its texture? What if we did that when the container gui is open, we have it switch to a texture of "open". It doesn't need to be be smooth. Just an idea, but I have no idea if this is possible. I have only been working with Fabric for a small time.

**Comment by FakeDomi** [comment]
Custom block states are not possible without a server side mod or lots of client side hacks
