### ISSUE TITLE
Chests invisible until you apply the provided classic-chest-model.zip resource pack

### ISSUE THREAD

**Issue by DrivingToTesco** [FakeDomi/FastChest#45]
Hi! Me and my friends were setting up FastChest 1.7+1.20.2 on Fabric 1.21.1. For a little bit, we were confused why our chests were invisible. We made sure all resource packs were off, and updated/removed any mod that effects rendering, with no luck. Even checked logs for some kind of errors. We even created fresh MultiMC instances with just FabricAPI + Sodium, just in case something was weird in our installations.

Eventually we found out we need the provided classic-chest-model.zip. We loaded that resource pack at the top of our list, and FastChest worked perfect (including ModMenu toggle). 

Is this intended behavior? I don't think it's very clear within the readme, if it's intended. Perhaps there's an issue with the simplified model if it's included in the mod. 

Thanks for the awesome mod! I go from 20fps to 200fps in our vault now!
![image](https://github.com/user-attachments/assets/667cabe9-8d6e-4f39-9aac-49524f17a126)

**Comment by FakeDomi** [comment]
I cannot recreate this with MC 1.21.1 and the latest versions of Fabric Loader, API, Sodium and FastChest. Are you absolutely sure you didn't have any resource packs enabled? Invisible chests sound like a resource pack problem, especially if it's fixed by using the (optional) classic chest model pack with higher priority.

**Comment by DrivingToTesco** [comment]
I did a little more experimentation.

I copied everything from my strange-behaving instance to a new one. All my mods and resource packs (modlist below). On this new instance, with the same exact resource pack configuration (Fabric mods at the top, my custom pack unloaded), Fastchest works perfect. On my other instance, I have the vanilla chest model, with no opening lid.

Everything is fixed once I apply that classic-chest-model pack to the top of the broken instance

I'm about to call this some kind of Minecraft problem, unless you have any more idea than me lol. None of these mods should really effect chest texture i think 
![image](https://github.com/user-attachments/assets/5cb3e11e-d3ef-486c-86d5-25524a5c0d5b)
![image](https://github.com/user-attachments/assets/8e9c2157-8412-490f-b9b3-07147a2694c3)

**Comment by FakeDomi** [comment]
None should, but it's still possible one of these mods does something funky.
I guess trapped and ender chests won't be visible either. If you know how to make a resource pack, you can turn this mod's resources into its own resource pack to make sure it's on top.
