### ISSUE TITLE
missing texture problem

### ISSUE THREAD

**Issue by unrealmanchen** [FakeDomi/FastChest#6]
I found that if the other texture you are using has files named "chest.json" "ender_chest.json" "trapped_chest.json" in the assets/minecraft/models/item , will cause missing texture problem look like in my picture. Delete them will fix this problem 

Is it only my texture problem or most of the textures have the same problem?_
![截屏2021-02-18 下午5 40 49](https://user-images.githubusercontent.com/67812862/108337828-83ba4d00-7210-11eb-9458-6f7120c464a1.png)
![截屏2021-02-18 下午5 41 01](https://user-images.githubusercontent.com/67812862/108337841-874dd400-7210-11eb-9115-b3d7d27a6a27.png)

_

**Comment by FakeDomi** [comment]
That's a known problem with resource packs overwriting these files. And it's how Minecraft intends resource packs to work.
It shouldn't be a problem with most resource packs though, as there are very few reasons to include those files.

**Comment by unrealmanchen** [comment]
Thanks for answering it
