### ISSUE TITLE
1.15.2 crash

### ISSUE THREAD

**Issue by R1ckyH** [FakeDomi/FastChest#7]
The game crashed whilst rendering overlay
Error: java.lang.NoSuchMethodError: 'java.nio.file.Path net.fabricmc.loader.api.FabricLoader.getConfigDir()'
error code -1
[crash-2021-02-22_13.43.54-client.txt](https://github.com/FakeDomi/FastChest/files/6019728/crash-2021-02-22_13.43.54-client.txt)

minecraft fabric 0.8.5 build 199 1.15.2

**Comment by R1ckyH** [comment]
btw thank you very much for update 1.15

**Comment by FakeDomi** [comment]
Update Fabric loader
