### ISSUE TITLE
Mark as client mod in fabric.mod.json

### ISSUE THREAD

**Issue by Sanluli36li** [FakeDomi/FastChest#8]
This is just a mod to improve Chest rendering, and it does not need to be applied to the server . So I recommend marking it as a client mod in `fabric.mod.json`

```
  "icon": "assets/fastchest/icon.png",

  "environment": "client",
  "entrypoints": {
```

**Comment by FakeDomi** [comment]
It seems the field only serves an informational purpose. The mod still "loads" on the server without any complaints or warnings.
I set it to client only in the json now, but I won't make a new build just for that.
