### ISSUE TITLE
Expanded Storage support

### ISSUE THREAD

**Issue by srnyx** [FakeDomi/FastChest#9]
https://www.curseforge.com/minecraft/mc-mods/fastchest?comment=26

**Comment by FakeDomi** [comment]
I saw your comment on curse, and I was gonna say you'd have better luck asking the people over there at Expanded Storage.
But somebody already requested the same thing on their bug tracker (https://github.com/NinjaPhenix/FabricMods/issues/87) so you should keep an eye on that.
